# Generated by Django 4.0 on 2022-03-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedemptionII', '0007_bestemployee'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='团队名')),
                ('age', models.IntegerField(verbose_name='成员数量')),
                ('img', models.FileField(max_length=128, upload_to='', verbose_name='LOGO')),
            ],
        ),
    ]
