# Generated by Django 4.0 on 2022-03-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedemptionII', '0008_bestteam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bestteam',
            old_name='age',
            new_name='count',
        ),
        migrations.AlterField(
            model_name='bestteam',
            name='img',
            field=models.FileField(max_length=128, upload_to='team/', verbose_name='LOGO'),
        ),
    ]
